### ISSUE TITLE
KDE Wayland crash after few hours

### ISSUE THREAD

**Issue by Cyrix126** [Cyrix126/gupaxx#10]
## OS & Version:
e.g: Kde Neon 6.0, kernel 6.2.0-33-generic, Wayland Gupax v1.3.1

## Bug
Gupaxx crash after a few hours.

Terminal will output indefinitly
`Protocol error 0 on object wl_registry@2:`

Gupaxx crash output:
```
PanicInfo {
    payload: Any { .. },
    message: Some(
        called `Result::unwrap()` on an `Err` value: WinitEventLoop(ExitFailure(1)),
    ),
    location: Location {
        file: "<redacted>",
        line: 0,
        col: 0,
    },
    can_unwind: true,
    force_no_backtrace: false,
}

info:
   OS      | Linux
   args    | ArgsOs { inner: ["target/release/gupaxx"] }
   commit  | 300bc9c111b373ce091aed930cee98cff13fbdbe
   gupaxx   | v1.1.1
   p2pool  | v3.10 (bundled)
   xmrig   | v6.21.1 (bundled)
   uptime  | 32543.53 seconds

stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  11: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:392:3
  12: <unknown>

```

Note: need to try to reproduce.

**Comment by Cyrix126** [comment]
seems to come from a crash of Plasma wayland, not Gupaxx related.

**Comment by hassan0ibrahim** [comment]
I have the same problem on manjaro

**Comment by Cyrix126** [comment]
> I have the same problem on manjaro

Are you using wayland too ?

**Comment by Cyrix126** [comment]
Could be fixed by updating the [winit](https://github.com/rust-windowing/winit) crate which is a dep of [eframe](https://github.com/emilk/egui/tree/master/crates/eframe) since there is apparently a fix for this in the changelog of [v0.30.4](https://github.com/rust-windowing/winit/releases/tag/v0.30.4).

eframe does not have a release including the commit yet, but the git can be included directly in the Cargo.toml

The new version does have breaking change that needs to be taken care.

**Comment by hassan0ibrahim** [comment]
> > I have the same problem on manjaro
> 
> Are you using wayland too ?

No I'm using Xorg

**Comment by hassan0ibrahim** [comment]
> Could be fixed by updating the [winit](https://github.com/rust-windowing/winit) crate which is a dep of [eframe](https://github.com/emilk/egui/tree/master/crates/eframe) since there is apparently a fix for this in the changelog of [v0.30.4](https://github.com/rust-windowing/winit/releases/tag/v0.30.4).
> 
> eframe does not have a release including the commit yet, but the git can be included directly in the Cargo.toml
> 
> The new version does have breaking change that needs to be taken care.

can you explain more

**Comment by Cyrix126** [comment]
> No I'm using Xorg

Can you post the terminal output when it is crashing and the crash report ? you can find it inside ~/.local/share/gupaxx/crash.log

**Comment by hassan0ibrahim** [comment]
> > No I'm using Xorg
> 
> Can you post the terminal output when it is crashing and the crash report ? you can find it inside ~/.local/share/gupaxx/crash.log

> No I'm using Xorg

Can you post the terminal output when it is crashing and the crash report ? you can find it inside ~/.local/share/gupaxx/crash.log

**Comment by hassan0ibrahim** [comment]
> > No I'm using Xorg
> 
> Can you post the terminal output when it is crashing and the crash report ? you can find it inside ~/.local/share/gupaxx/crash.log

mass_panic!() - Saved panic log to: /home/ceo/.local/share/gupaxx/crash.txt

----- MASS PANIC: src/utils/panic.rs @ 46 -----
PanicHookInfo {
    payload: Any { .. },
    location: Location {
        file: "<redacted>",
        line: 0,
        col: 0,
    },
    can_unwind: true,
    force_no_backtrace: false,
}

info:
   OS      | Linux
   args    | ArgsOs { inner: ["./gupaxx-v1.3.1-linux-x64-bundle/gupaxx"] }
   commit  | baa70cd458e7a22689811a2b1d9576eb2d274083
   gupaxx   | v1.3.1
   p2pool  | v4.0 (bundled)
   xmrig   | v6.21.1 (bundled)
   uptime  | 0.41900462 seconds

stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: __libc_start_main
  12: <unknown>

----- EXITING ALL THREADS -----

**Comment by Cyrix126** [comment]
uptime | 0.41900462 seconds
Is it crashing at start ?

**Comment by hassan0ibrahim** [comment]
It started happening when I swapped my Rx570 graphics card with an older radeon hd card. I've tried several distros manjaro/void/arch

**Comment by hassan0ibrahim** [comment]
> > with an older radeon hd card
> 
> Which model ?

Radeon hd 6450

**Comment by Cyrix126** [comment]
I need the log file that you can enable starting gupaxx with --logfile.  It will write a log file into ~/.local/share/gupaxx. I need the log to better debug the issue you have with the old gpu which in theory should work since it supports the minimal opengl version required. Be aware the log can contains sensitive info like the xmr address and the xvb token. Feel free to remove them from the log file.

You can send it to me over matrix, I sent you an invite.

Could you also try the dev branch which updates dependencies possibly related to the issue ? you can download the binaries generated by the CI.

**Comment by Cyrix126** [comment]
@hassan0ibrahim I will rename this issue as a KDE bug since I can reproduce on this system. However since I don't have a reply from you since, feel free to open a new issue.

**Comment by Cyrix126** [comment]
More complete debug info:

```
----- MASS PANIC: src/utils/panic.rs @ 50 -----
PanicHookInfo {
    payload: Any { .. },
    location: Location {
        file: "/home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-wgpu-0.29.1/src/winit.rs",
        line: 173,
        col: 18,
    },
    can_unwind: true,
    force_no_backtrace: false,
}

info:
   OS          | Linux
   args        | ArgsOs { inner: ["target/release/gupaxx"] }
   commit      | 0949458d8562558016e24ed9dd594412e8372d71
   gupaxx      | v1.5.0
   monerod     | v18.3.4 (bundled) 
   p2pool      | v4.1.1 (bundled)
   xmrig       | v6.21.1 (bundled)
   xmrig-proxy | v6.21.1 (bundled)
   uptime      | 2619.7266 seconds

stack backtrace:
   0: gupaxx::utils::panic::set_panic_hook::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::option::expect_failed
   7: egui_wgpu::winit::Painter::configure_surface
   8: egui_wgpu::winit::Painter::resize_and_generate_depth_texture_view_and_msaa_view
   9: <eframe::native::run::WinitAppWrapper<T> as winit::application::ApplicationHandler<eframe::native::winit_integration::UserEvent>>::window_event
  10: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  11: winit::platform_impl::linux::wayland::event_loop::EventLoop<T>::pump_events
  12: eframe::native::run::run_wgpu
  13: gupaxx::main
  14: std::sys::backtrace::__rust_begin_short_backtrace
  15: main
  16: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  17: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:392:3
  18: _start

----- EXITING ALL THREADS -----
```

The crash comes from the egui-winit crates with an expect on a Null.
https://github.com/emilk/egui/blob/7bd6f83f18af7317f75e7a32413a9a9eb747db7f/crates/egui-wgpu/src/winit.rs#L173

**Comment by Cyrix126** [comment]
Seems to crash more frequently when the screen light goes off, but not every time.

**Comment by Cyrix126** [comment]
I can't reproduce it anymore after updating KDE nenon to 24.04 and Gupaxx to v1.5.1
