### ISSUE TITLE
Adding config file to Xmrig

### ISSUE THREAD

**Issue by hassan0ibrahim** [Cyrix126/gupaxx#13]
Adding config file to Xmrig
I tried to put a config.json in the Xmrig directory inside gupax folder but it wasn't used

**Comment by Cyrix126** [comment]
xmrig is started using the [http api option](https://xmrig.com/docs/miner/command-line-options#api). The config file can only be modified by using the API (you send your custom config in a POST request which will replace the current config).
You can see how it works here:
https://xmrig.com/docs/miner/api/config
https://github.com/xmrig/xmrig/blob/master/doc/API.md

Also note that if the XvB tab is used, the pools/rig-id,user,url values will be overridden. You can however change any other values as you wish.

**Comment by hassan0ibrahim** [comment]
So what arguments should i input exactly in xmrig tab

**Comment by Cyrix126** [comment]
> So what arguments should i input exactly in xmrig tab

It depends on what you want to do. You can see available options starting xmrig with `--help` arg in a terminal.

If you want to replace the current config file of xmrig started by Gupaxx, look at this  [curl command](https://github.com/xmrig/xmrig/blob/master/doc/API.md#put-1config)  and replace the port by the one used by xmrig http API (you can see it in the console tab of xmrig once started), and also replace the SECRET by the token inside the state.toml file in the local data directory of Gupaxx under the section "xmrig" (~/.local/share/gupaxx for Linux, ~/AppData/Roaming/Gupaxx for Windows).
