### ISSUE TITLE
When building Xmrig from source the status tab doesn't work even when adding --http-host 127.0.0.1 --http-port 18088 to command arguments

### ISSUE THREAD

**Issue by hassan0ibrahim** [Cyrix126/gupaxx#14]
## OS & Version:
Linux and Windows, Gupax v1.3.3

## Bug
When building Xmrig from source the status tab doesn't work even when adding --http-host 127.0.0.1 --http-port 18088 to command arguments
## Steps
sudo pacman -S base-devel cmake hwloc
git clone https://github.com/xmrig/xmrig.git
cd xmrig
mkdir build && cd $_
cmake .. -DWITH_HTTPD=OFF
make
If your replaced xmrig/build/xmrig with the xmrig in gupaxx dir. the status tab doesn't work even with command arguments added

**Comment by Cyrix126** [comment]
> doesn't work

It is not descriptive enough.

If however it is hashrate of xmrig not showing up for 15mn, you can try the dev branch of xmrig which should include a [fix](https://github.com/xmrig/xmrig/commit/b4a47d6ed00022abd82d3e1ee062ec8796bb26d5) that once released, will make me include a newer build of xmrig.

In any case, only the xmrig build included in the releases is supported (which are directly taken from the xmrig releases).

**Comment by hassan0ibrahim** [comment]
Thank you the dev branch worked
