### ISSUE TITLE
Minimal VIP miner raffle

### ISSUE THREAD

**Issue by anon-erpk** [Cyrix126/gupaxx#15]
**Feature request**
With this option, Gupaxx will mine until you have a share in the main or mini sidechain PPLNS window, then will proceed to mine on another pool and not only donating to xmrvsbeast

**Additional context**
I would keep mining on p2pool for a chance to win the raffle bonus, but at the same time I would like to mine on MoneroOcean.
I tried to compile my own modified but I don't have much experience and I'm having an error when trying to compile using cargo:

"error: failed to run custom build command for `gupaxx v1.3.2 (C:\gupaxx-main)`

Caused by:
  process didn't exit successfully: `C:\gupaxx-main\target\debug\build\gupaxx-2a030444741870e4\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=.git/refs/heads/

  --- stderr
  thread 'main' panicked at build.rs:49:5:
  assertion failed: commit.len() >= 40"

**Comment by Cyrix126** [comment]
As stated in the README, Gupaxx is made to make mining on p2pool easy. The raffle is there to incentive mining on p2pool. Supporting centralized pools is not a goal of this project.
