### ISSUE TITLE
failed to start WinRing0 driver: "WinRing0x64.sys not found"

### ISSUE THREAD

**Issue by DeanLemans** [Cyrix126/gupaxx#16]
## OS & Version:
Windows 11, Gupax v1.4.2

## Bug
failed to start WinRing0 driver: "WinRing0x64.sys not found"

## Steps
1. Go to xmrig
2. Click on start
3. See error

## Screenshots
![image](https://github.com/user-attachments/assets/0f8f5712-593b-4a2f-903e-0c32961861ee)

## Crash report
If Gupax is crashing, please paste the file here:
Gupaxx is not crashing

## further explanation
when starting xmrig I get a message that winring0 is not found.
I am using version 1.4.2 and I used the gupaxx-v1.4.2-windows-x64-bundle.zip 

and yes I ran it as administrator, on the gupaxx.exe in the folder.
and I also added the folder to the windows firewall exceptions.

reinstalled the zip again and extracted it for the second time. I still get the same error.

**Comment by Cyrix126** [comment]
This issue comes from xmrig.
There are some results for it.
https://github.com/xmrig/xmrig/issues?q=is%3Aissue+WinRing+

Possible solutions:
- put the file https://github.com/xmrig/xmrig/blob/master/bin/WinRing0/WinRing0x64.sys in the same directory as xmrig binary.

- install Open Hardware Monitor 

- disable secure boot

Please try.

**Comment by DeanLemans** [comment]
tested on: windows 11

can confirm that downloading and copying the https://github.com/xmrig/xmrig/blob/master/bin/WinRing0/WinRing0x64.sys into the XMRig folder fixes the issue.

![image](https://github.com/user-attachments/assets/a5d7e313-66c2-49d1-97c0-f8fec05938c8)

but why isnt the WinRing0x64.sys file included by default?
is this a XMRig issue?

and if so can you maby consider including it by default?
