### ISSUE TITLE
Windows: Size of Node DB at 0B 

### ISSUE THREAD

**Issue by Cyrix126** [Cyrix126/gupaxx#19]
Originally reported by @MKRajan29 in https://github.com/Cyrix126/gupaxx/issues/18
## OS & Version:
Windows 10 & Windows 11

## Bug
In the Status tab on Process sub-menu, the size of the DB will stay at 0B
## Steps
1. Start Monerod
2. Click on Status Tab process submenu
3. See error on column "Node".

## Screenshots
![image](https://github.com/user-attachments/assets/2d06224e-4b5a-4f45-8f31-e594d4094e1e)

## Additional context
Linux is not affected.

### Note to myself
Need to see what's the output of /json_rpc with method get_info on Windows. Tried with curl but I'm getting parse output error when the same arguments works on Linux. The http client in Gupaxx seems to be doing fine since the rest of the stats are available. Need to run the monerod on Windows and try to get a response from Linux.

EDIT: on Windows, you need to escape the quotes.
`curl -d "{\"jsonrpc\":\"2.0\",\"id\":\"0\",\"method\":\"get_info\"}" http://127.0.0.1:18081/json_rpc`

**Comment by Cyrix126** [comment]
https://github.com/monero-project/monero/issues/9513

**Comment by Cyrix126** [comment]
[fixed in https://github.com/Cyrix126/gupaxx/releases](https://github.com/Cyrix126/gupaxx/releases/tag/v1.5.1) by reading the size of the DB directly from the filesystem.

**Comment by MKRajan29** [comment]
The issue seems to be existing even after updating Gupaxx to 1.5.1

**Comment by Cyrix126** [comment]
> The issue seems to be existing even after updating Gupaxx to 1.5.1

Please post a screenshot of the column Node of Tab Status including the version of Gupaxx at the bottom left.

**Comment by MKRajan29** [comment]
Sure

![image](https://github.com/user-attachments/assets/2d30733a-b9af-4613-873c-91ee865a73f3)

> Please also tell if you are using a custom directory or not and which version of Windows.
When the Node start, the path of the DB will be displayed in the console. Could you post it (removing any necessary private info) ?.

Indeed a custom directory. Win 11 Ver 23H2

![image](https://github.com/user-attachments/assets/e56999f0-b869-4ea7-a3b7-7032e700af61)

**Comment by Cyrix126** [comment]
Strangely, I can't reproduce the 0B, but it is stuck at 4.096 KB on a W10 VM.
Will investigate.

**Comment by Cyrix126** [comment]
ok it must be surely because I made it look at the directory instead of the file when I wanted to make it work also for simple mode, didn't check after this change apparently.

**Comment by Cyrix126** [comment]
fixed in https://github.com/Cyrix126/gupaxx/commit/044526abd3199f2d4ee00f68feefda2007c1c858
Will let open until included in a release.
Thanks @MKRajan29 !

**Comment by MKRajan29** [comment]
Hey bud,

In the Status Tab, in the XMRig Column, the Pool Heading is still 'XvB European Node' even though I have no shares and no hash is being sent to the XvB Node and it is only hashing on the local node. It seems either it is not refreshing the said status or it thinks otherwise. 

The XvB Raffle is always on the Round Type = "Mega Donor", maybe am seeing it only when it is the case or is there something broken there.

Also I don't know what is the purpose of [0.00, 0.00, 0.00] in the XMRig Uptime.

**Comment by Cyrix126** [comment]
> Hey bud,
> 
> In the Status Tab, in the XMRig Column, the Pool Heading is still 'XvB European Node' even though I have no shares and no hash is being sent to the XvB Node and it is only hashing on the local node. It seems either it is not refreshing the said status or it thinks otherwise.
> 
> The XvB Raffle is always on the Round Type = "Mega Donor", maybe am seeing it only when it is the case or is there something broken there.
> 
> Also I don't know what is the purpose of [0.00, 0.00, 0.00] in the XMRig Uptime.

Please open other issues to keep things separate.

**Comment by Cyrix126** [comment]
closed by release [v1.5.2](https://github.com/Cyrix126/gupaxx/releases/tag/v1.5.2)

**Comment by MKRajan29** [comment]
The issue still persists.

**Comment by Cyrix126** [comment]
> The issue still persists even in ver 1.5.3

Thanks for reporting. Indeed there was still an issue for custom db path.
It should be fixed with https://github.com/Cyrix126/gupaxx/commit/0bf41fde586c96b7a89259178138014354dcf9d9
Could you test the binary produced for windows here (maybe have to wait a bit for CI to finish)
https://github.com/Cyrix126/gupaxx/actions/runs/11893193482

**Comment by Cyrix126** [comment]
[v1.5.4](https://github.com/Cyrix126/gupaxx/releases/tag/v1.5.4)

**Comment by MKRajan29** [comment]
The issue persists on windows.

**Comment by Cyrix126** [comment]
> The issue persists on windows.

Is it working  for simple mode ? 
What does the line of "Loading blockchain from folder" says in simple mode ?

**Comment by MKRajan29** [comment]
There is nothing in Simple Mode, the page is empty.

![image](https://github.com/user-attachments/assets/23b09d13-b5e0-4399-b7cf-da9b0d7851f4)

**Comment by Cyrix126** [comment]
Yes that's expected. But when you restart the Node in simple mode, you have a line "Loading blockchain from folder...", what is the path ?

And starting the Node in simple mode, does it show the good value of size in Status tab ?

**Comment by MKRajan29** [comment]
The path in Simple Mode when restarted in this way is "C:\ProgramData\bitmonero\lmdb ..." which is not custom path set in the advanced mode.

Also starting the node in simple mode forces the blockchain to sync from beginning. Writing this from v1.6.0

**Comment by Cyrix126** [comment]
> The path in Simple Mode when restarted in this way is "C:\ProgramData\bitmonero\lmdb ..." which is not custom path set in the advanced mode.
> 
> Also starting the node in simple mode forces the blockchain to sync from beginning. Writing this from v1.6.0

Changing thé path back to jour custom path will continue where it was. Do you still have a wrong size in either simple or advanced ?
