### ISSUE TITLE
update bundled xmrig-proxy from v6.21.1 to v6.22.0

### ISSUE THREAD

**Issue by DeanLemans** [Cyrix126/gupaxx#22]
**Feature request**
update bundled xmrig-proxy to the latest version(currently newest version is [v6.22.0.](https://github.com/xmrig/xmrig-proxy/releases) )

**Additional context**
In the latest release of gupaxx(v1.5.1) it mentions that the bundled version is v6.21.1 when the latest release of xmrig-proxy is [v6.22.0.](https://github.com/xmrig/xmrig-proxy/releases)

**Comment by Cyrix126** [comment]
let's close this issue in favor of #20 since it is for the same reason.
