### ISSUE TITLE
dont enable "use local node" by default

### ISSUE THREAD

**Issue by DeanLemans** [Cyrix126/gupaxx#23]
**Feature request**
please don't enable use local node by default

**Additional context**
please don't enable use local node by default in the p2pool tab: 
1. new users have no idea what they are doing and could get confused by why so much storage got taken out of nowhere.(if they sync the node of course but the point still stands)
2.  the bar of entry will rise for new (noob/beginner) users

(possible) solutions:
1. don't enable "use local node by default" in the p2pool tab.
2. maby check if the user already has a synced node and then show this option.

**Comment by Cyrix126** [comment]
I don't agree for the following reasons:
### Trustless:
1. Users might expect mining by default in the most decentralized way. It is not said explicitly in the README but I want one of the goal to make decentralized mining easy (right now it says p2pool mining made easy, which is almost the same thing).
2. Remotes nodes can be offline or controlled by an entity who does not care about the user interests. The user don't have any control over them. It is more prudent to let the surest but slower option by default.
### User friendly concerns:
4. New users just have to start the Node in simple mode with one button, if node already auto-started. A help text is written when you hover the checkbox explaining what to do. 
5. The issue of size taken is mediated by the fact that prunning is enabled by default. A warning could be added to make it more clear that space is required. The size taken by the database can be seen on the Status tab, I think it is hard to miss.


However things can be made to make the user friendly part better:

P2Pool start could be prevented if the option is checked and the local node is not started (P2Pool will be fine even if the node is not synced, it will wait for it before syncing itself). A hover text on the start button will explain why the start is not possible. For Auto-Start, I will need to make sure the node start before.

Also in the future, a mode "beginner" and a mode "setup guide" will exist, see https://github.com/Cyrix126/gupaxx/blob/main/IDEAS.md#setup-guide and https://github.com/Cyrix126/gupaxx/blob/main/IDEAS.md#very-noob-mode.

**Comment by Cyrix126** [comment]
Still open to debate to what the majority of users wants.
Also I can add a feature: let Gupaxx use a remote node while in the same time syncing a local node. Once the local node is synced, switch to it.

**Comment by Cyrix126** [comment]
After reflection and discussion on matrix,I now agree that the default will be remotes nodes with warnings and detection of local node. Impact on storage and (small) HR impact could surprise the user if they don't know what it is, it will make noob users leave when it would at least be better for the network to let them to at least use a remote node and mine on p2pool.
https://github.com/Cyrix126/gupaxx/blob/main/IDEAS.md#better-default

**Comment by MKRajan29** [comment]
Will this reflect on every future builds?

**Comment by Cyrix126** [comment]
> Will this reflect on every future builds?

Updates will not overwrite the configuration file. So the default (using remotes nodes) will be active only for new downloads.

**Comment by Cyrix126** [comment]
option is unselected by default with https://github.com/Cyrix126/gupaxx/commit/6cb767a342bec2df3358b10826a1ec1dee57fc76
Will add more features later about detection of local node and using remotes while syncing.
Issue will be close at next release.

**Comment by Cyrix126** [comment]
closed by release [v1.5.2](https://github.com/Cyrix126/gupaxx/releases/tag/v1.5.2)
