### ISSUE TITLE
Proxy stats never appear, preventing the XvB algorithm from ever starting

### ISSUE THREAD

**Issue by Slipstreamm** [Cyrix126/gupaxx#24]
## OS & Version:
Windows 11, Gupaxx v1.5.1

## Bug
The hashrates for XMRig-Proxy in the status tab eternally stay at 0, which means the XvB algorithm never starts as it doesn't get the 1 minute average HR  

## Steps
Start XMRig-Proxy
Start XMRig
Go to status tab
Proxy average hashrates are at zero forever

## Screenshots
Also waited for about 3 hours before
![image](https://github.com/user-attachments/assets/9dc3887b-608d-459f-8996-109cf0582b8d)
![image](https://github.com/user-attachments/assets/b02d881a-b10b-467e-8a3a-10ecc57b583d)

**Comment by MKRajan29** [comment]
What's the set of zeros in the XMrig Uptime?

**Comment by Slipstreamm** [comment]
> What's the set of zeros in the XMrig Uptime?

Not entirely sure, here's the output of /2/summary in the http api, maybe its the load average? Thats the only thing with 3 zeroes. Also could have something to do with the fact I'm using my own build of 6.22.0 xmrig with the donate level at 0

FYI i closed the issue cause a restart fixed it, i have no idea why it didnt occur to me to try restarting before making a whole github issue

`{
    "id": "60110d2551f9a347",
    "worker_id": "Hyperion",
    "uptime": 7222,
    "restricted": false,
    "resources": {
        "memory": {
            "free": 20400807936,
            "total": 34051969024,
            "resident_set_memory": 17993728
        },
        "load_average": [0.0, 0.0, 0.0],
        "hardware_concurrency": 16
    },
    "features": ["api", "asm", "http", "hwloc", "tls", "opencl", "cuda"],
    "results": {
        "diff_current": 722328,
        "shares_good": 203,
        "shares_total": 203,
        "avg_time": 35,
        "avg_time_ms": 35525,
        "hashes_total": 85500694,
        "best": [274379766, 85017943, 66948178, 12197611, 11940826, 11035971, 10888115, 9380502, 7133215, 6463694]
    },
    "algo": "rx/0",
    "connection": {
        "pool": "127.0.0.1:3355",
        "ip": "127.0.0.1",
        "uptime": 7211,
        "uptime_ms": 7211741,
        "ping": 1,
        "failures": 0,
        "tls": null,
        "tls-fingerprint": null,
        "algo": "rx/0",
        "diff": 722328,
        "accepted": 203,
        "rejected": 0,
        "avg_time": 35,
        "avg_time_ms": 35525,
        "hashes_total": 85500694
    },
    "version": "6.22.0",
    "kind": "miner",
    "ua": "XMRig/6.22.0 (Windows NT 10.0; Win64; x64) libuv/1.48.0 msvc/2022",
    "cpu": {
        "brand": "AMD Ryzen 7 7800X3D 8-Core Processor",
        "family": 25,
        "model": 97,
        "stepping": 2,
        "proc_info": 10882834,
        "aes": true,
        "avx2": true,
        "x64": true,
        "64_bit": true,
        "l2": 8388608,
        "l3": 100663296,
        "cores": 8,
        "threads": 16,
        "packages": 1,
        "nodes": 1,
        "backend": "hwloc/2.10.0",
        "msr": "ryzen_19h_zen4",
        "assembly": "ryzen",
        "arch": "x86_64",
        "flags": ["aes", "vaes", "avx", "avx2", "avx512f", "bmi2", "osxsave", "pdpe1gb", "sse2", "ssse3", "sse4.1", "popcnt", "cat_l3"]
    },
    "donate_level": 0,
    "paused": false,
    "algorithms": ["cn/0", "cn/1", "cn/2", "cn/r", "cn/fast", "cn/half", "cn/xao", "cn/rto", "cn/rwz", "cn/zls", "cn/double", "cn/ccx", "cn-lite/0", "cn-lite/1", "cn-heavy/0", "cn-heavy/tube", "cn-heavy/xhv", "cn-pico", "cn-pico/tlo", "cn/upx2", "rx/0", "rx/wow", "rx/arq", "rx/graft", "rx/sfx", "rx/yada", "argon2/chukwa", "argon2/chukwav2", "argon2/ninja", "ghostrider"],
    "hashrate": {
        "total": [11699.68, 11349.53, 11280.33],
        "highest": 12153.71
    },
    "hugepages": [1184, 1184]
}`
