### ISSUE TITLE
XMRig Pool in XvB Node even without any share.

### ISSUE THREAD

**Issue by MKRajan29** [Cyrix126/gupaxx#25]
## OS & Version:
e.g: Windows 11, Gupaxx v1.5.1

## Bug
In the Status Tab, in the XMRig Column, the Pool Heading is still 'XvB European Node' even though I have no shares and no hash is being sent to the XvB Node and it is only hashing on the local node. It seems either it is not refreshing the said status or it thinks otherwise.

## Steps
1. Go to Status Tab.
2. View the XMRig Column after there is no share or expired.
4. The Pool header should show the localhost but it is showing XvB European Node even though no hash is being sent, I presume.
5. View the XvB Tab, there is no hash being sent to XvB but P2Pool is what the message says.

## Screenshots
![image](https://github.com/user-attachments/assets/d0ffde48-e594-496c-a72c-b180777cbfb3)
![image](https://github.com/user-attachments/assets/7062335f-4a61-4b45-8e06-f2ed30d613f3)

## Crash report
If Gupaxx is crashing, you may have a file here:
No crashing.

**Comment by Cyrix126** [comment]
note: same for xmrig-proxy.

**Comment by Cyrix126** [comment]
fixed by https://github.com/Cyrix126/gupaxx/commit/7874e75f70d30718be3ff772eed37af8c3443530.
Issue will be closed at next release.

**Comment by Cyrix126** [comment]
closed by release [v1.5.2](https://github.com/Cyrix126/gupaxx/releases/tag/v1.5.2)
