### ISSUE TITLE
rig-id is used for XvB when XMRig tab is on advanced sub-menu

### ISSUE THREAD

**Issue by Cyrix126** [Cyrix126/gupaxx#3]
## OS & Version:
Gupaxx =< v1.0.0

## Bug
XvB node will see rig-id as the worker name instead of username set by -u option of xmrig.

## Steps
1. Go to XMRig Tab
2. Click on sub-menu Advanced instead of simple
3. Start P2pool, XMRig and XvB process
4. If algo is sending HR to XvB, it will not be accounted for

**Comment by Cyrix126** [comment]
This issue will be solved in release v1.0.1
The rig-id will be removed when mining on XvB and reset for p2pool mining (in the case an advanced need this value for his p2pool node).

temporary fix: put XMRig tab on simple sub-menu.

**Comment by Cyrix126** [comment]
fixed by https://github.com/Cyrix126/gupaxx/commit/9613e9ef994c973fdac3117567ff447634e116cf
Issue will be closed when commit will be in release.

**Comment by CompKingCanada** [comment]
When will this be released?  I was wondering why I wasn't getting any credit for donated hash rate.  Grrr...

**Comment by Cyrix126** [comment]
> When will this be released? I was wondering why I wasn't getting any credit for donated hash rate. Grrr...

Hello, sorry for the inconvenience.
I want to solve all other issues before getting a release. It should takes no more than a few days.

**Comment by Cyrix126** [comment]
fixed in release [1.1.0](https://github.com/Cyrix126/gupaxx/releases/tag/v1.1.0)
