### ISSUE TITLE
dont run .MD through github action

### ISSUE THREAD

**Issue by DeanLemans** [Cyrix126/gupaxx#40]
## OS & Version:
e.g: Windows 11, Gupaxx v1.4.2

## Bug
What is the bug?

gupaxx workflow is checking .MD file changes when its not necessary

## Steps
1. create PR with changed to .MD files
2. got to [github action tab](https://github.com/Cyrix126/gupaxx/actions)
3. See error

## Screenshots
If possible, add screenshots to help explain the bug.
![image](https://github.com/user-attachments/assets/4777f767-4b8c-441d-8a91-1ba2ce81e358)

## Crash report
If Gupaxx is crashing, you may have a file here:

gupaxx is not crashing

## Additional context

changing .MD files shouldn't run the workflow at all(i think), so you could add them to exception, this should be in one of the files in the .github/workflows folder(idk which one though, or how to change it).

**Comment by Cyrix126** [comment]
it should run only the typo check. Indeed the rest is not useful.

**Comment by Cyrix126** [comment]
Fixed with https://github.com/Cyrix126/gupaxx/commit/f9f3faf03dc3f7daef61091656b24f68a46a362e, https://github.com/Cyrix126/gupaxx/commit/b487c0c40619cdd44d53becfbd5eb5fce6b2abc9 and https://github.com/Cyrix126/gupaxx/commit/3f88ae9c6d7a6b17290c7cffe8ecc3eff884b5f6
