### ISSUE TITLE
system CPU model text is weirdly paced

### ISSUE THREAD

**Issue by DeanLemans** [Cyrix126/gupaxx#44]
## OS & Version:
Windows 11, Gupaxx v1.5.3

## Bug
system CPU model text is weirdly paced

## Steps
1. Go to 'status tab'
2. See error

## Screenshots
![2024-11-13 18_34_33-Greenshot](https://github.com/user-attachments/assets/6b6c1b45-97d0-400f-b9d4-4d73db4951aa)

## Crash report
x

## Additional context
it just looks weird.

**Comment by Cyrix126** [comment]
fixed in 50b3336156ee787cbfebe69b6e628e1a6d777969

**Comment by Cyrix126** [comment]
[v1.5.4](https://github.com/Cyrix126/gupaxx/releases/tag/v1.5.4)
