### ISSUE TITLE
extra space in node tab advanded

### ISSUE THREAD

**Issue by DeanLemans** [Cyrix126/gupaxx#45]
## OS & Version:
Windows 11, Gupaxx v1.5.3

## Bug
extra space in node tab advanded;

1. both out-peers and in-peers have an extra space in front of them compared to log level
2. log level has an extra space before the :

## Steps
1. Go to 'node tab'
3. Click on 'advanced'

## Screenshots
![2024-11-13 18_27_24-Greenshot](https://github.com/user-attachments/assets/6718f6b7-831a-498d-8547-37263ca727fb)

## Additional context
i think the bugs are related so i put them both in 1 bug report.

**Comment by Cyrix126** [comment]
fixed in 50b3336156ee787cbfebe69b6e628e1a6d777969.

**Comment by Cyrix126** [comment]
[v1.5.4](https://github.com/Cyrix126/gupaxx/releases/tag/v1.5.4)
