### ISSUE TITLE
add GPL logo to readme

### ISSUE THREAD

**Issue by DeanLemans** [Cyrix126/gupaxx#47]
**Feature request**
add the GPL logo to the [readme](https://github.com/Cyrix126/gupaxx#license)

**Additional context**
[logos](https://www.gnu.org/graphics/license-logos.html)

(I recommend the Alternative logos by Christian Cadena, as they look a bit more modern, but there is also the issue of people not being able to recognize them.)

**Comment by Cyrix126** [comment]
Why not, I'll approve a PR for it but I have a preference for the original logo. The new one also does not seem to be dark theme friendly with the black text.

**Comment by Cyrix126** [comment]
After all, I also accept the new logo.
