### ISSUE TITLE
Freeze on windows 10 after some days running

### ISSUE THREAD

**Issue by anon-erpk** [Cyrix126/gupaxx#6]
The UI stops answering after some days running, I don't know if the raffle algorithm is still running, but p2pool and xmrig are running ok

**Comment by Cyrix126** [comment]
Will try to reproduce with a VM.
What's your hardware (cpu/ram) and build version of Windows ? you can get these information with "About system"

**Comment by seatsea** [comment]
I can also report having this issue on W11
Additionally, even when the UI isn't frozen, the raffle algorithm also appears to frequently restart and loose track of the live data, sometimes causing seemingly excessive donation to the raffle. 

Hardware is AMD 5700X with 32GB of ram.

**Comment by Cyrix126** [comment]
how many days until the UI freeze ?

> Additionally, even when the UI isn't frozen, the raffle algorithm also appears to frequently restart and loose track of the live data, sometimes causing seemingly excessive donation to the raffle.

Can you open a new issue for it and give as much details as you can ?

**Comment by Cyrix126** [comment]
@anon-erpk @seatsea Can you tell me if new lines in the XvB tab console appears every minutes instead of every ten minutes when the UI is freezed or does it freeze also without this issue ?

**Comment by Cyrix126** [comment]
fixed in [1.1.1](https://github.com/Cyrix126/gupaxx/releases/tag/v1.1.1)

**Comment by Cyrix126** [comment]
fixed in [1.1.1](https://github.com/Cyrix126/gupaxx/releases/tag/v1.1.1)
